on:
  push:
    branches:
      - master
      - develop
      - release**
  pull_request:
    branches:
      - master
      - develop
      - release**
  schedule:
    - cron: '0 0 1 * *'

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-latest, r: '3.6', vdiffr: true }
        # There are currently issues installing r-devel on Windows on CI
        # - { os: windows-latest, r: 'devel', vdiffr: false }
        - { os: macOS-latest, r: '3.6', vdiffr: true }
        # The devel versions are changing quickly at the moment and often cause failures related to other packages. Remove for now.
        # - { os: macOS-latest, r: 'devel', vdiffr: false }
        # Rcpp currently fails to install for R 3.3 (2020-04-02)
        # - { os: ubuntu-16.04, r: '3.3', cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest", vdiffr: false }
        - { os: ubuntu-16.04, r: '3.4', cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest", vdiffr: false }
        - { os: ubuntu-16.04, r: '3.5', cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest", vdiffr: false }
        - { os: ubuntu-16.04, r: '3.6', cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest", vdiffr: true }
        # r-devel is not available on Ubuntu (ref. r-lib/actions/setup-r/lib/installer)
        - { os: ubuntu-latest, r: 'release', vdiffr: false }

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_FORCE_SUGGESTS_: false
      CRAN: ${{ matrix.config.cran }}
      # Runs vdiffr test only on the latest version of R
      VDIFFR_RUN_TESTS: ${{ matrix.config.vdiffr }}
      VDIFFR_LOG_PATH: "../vdiffr.Rout.fail"

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install XQuartz on macOS
        if: runner.os == 'macOS'
        run: brew cask install xquartz

      # To install vdiffr, these three libraries/tools are needed:
      # - freetype (already installed, needed by systemfonts)
      # - cairo (not installed, needed by gdtools)
      # - pkg-config (not installed, needed to set proper build settings)
      - name: Install pkg-config and cairo on devel macOS
        if: runner.os == 'macOS' && matrix.config.r == 'devel'
        run: brew install pkg-config cairo

      - name: Use drat for devel on macOS
        if: runner.os == 'macOS' && matrix.config.r == 'devel'
        run: |
          cat <<EOT >> .Rprofile
          r <- getOption("repos")
          r["CRAN"] <- "https://cran.rstudio.com"
          r["rccp_drat"] <- "https://RcppCore.github.io/drat"
          options(repos = r)
          EOT

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('DESCRIPTION') }}

      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "install.packages('remotes')" -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"

      - name: Install dependencies
        run: Rscript -e "install.packages('remotes')" -e "remotes::install_deps(dependencies = TRUE)" -e "remotes::install_cran('rcmdcheck')"

      - name: Check
        run: Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'warning', check_dir = 'check')"

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
